### PR TITLE
Support file+emacs and file+sys links

### PR DESCRIPTION
**Pull request by tchajed**
Fixes \#46.

### CODE REVIEW

**Comment by bzg** [comment]
It looks like the merge is safe for this. Is anything we can do to help?  Thanks!

**Comment by tchajed** [comment]
@vonavi: ping, could you take a look at this when you get the chance?

**Comment by vonavi** [comment]
Sorry, I don't have time to work on this project. On my mind, it is fairly to say that `org-ruby` is unsupported for a long time.

**Comment by tchajed** [comment]
Fair enough, thanks for the response!

**Comment by wallyqs** [comment]
Has been busy for me too... ok can try to take a look this Sunday.

**Comment by bzg** [comment]
Thanks for the merge!

**Pull request merged**
